name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.18.2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.18.2

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main

        npm run build

        rm -rf *
        cp -r dist/index.html
        git add .
        git commit -m "Deploy to GitHub Pages" --allow-empty
        git push origin main